name: Deploy to render

on:
  push:
    branches:
      - 0.0.0_render

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v7

      - name: Run build
        run: ./runrelease.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: 0.0.0_render_release
          folder: resources/public
